FROM tensorflow/tensorflow:latest-gpu-jupyter

RUN apt-get update && apt-get install -yq


RUN apt update && \
    apt install --no-install-recommends -y build-essential gcc && \
    apt clean && rm -rf /var/lib/apt/lists/*
COPY requirements.txt /requirments.txt

